name: flutter_application_progettomobile_pagani_ridolfi
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  logger: 2.0.2+1
  intl: ^0.17.0
  path_provider: ^2.1.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/nba_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        




  uses-material-design: true

  